-- Hyprland main config (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- === Environment ===
-- NVIDIA
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
-- Qt / Electron on Wayland
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- === Xwayland ===
hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- === DMS startup ===
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)

-- === Base config ===
hl.config({
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		force_split = 2,
	},
	decoration = {
		active_opacity = 1.0,
		inactive_opacity = 0.95,
	},
})

-- === Animations ===
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 2, bezier = "default" })

-- === DMS layer rules ===
hl.layer_rule({ match = { namespace = "^quickshell$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

-- === DMS fragments (auto-generated by `dms setup`, do not edit) ===
require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

-- === User fragments (own config) ===
require("configs.monitors")
require("configs.input")
require("configs.rules")
require("configs.keybinds")
require("configs.exec")
