# env = XDG_CURRENT_DESKTOP,Hyprland
# env = XDG_SESSION_TYPE,wayland
# env = XDG_SESSION_DESKTOP,Hyprland
# env = QT_QPA_PLATFORMTHEME,gtk3
# env = GTK_THEME,Adwaita-dark

# env = XCURSOR_SIZE,16
# env = HYPRCURSOR_SIZE,16
# env = XCURSOR_THEME,Adwaita
# env = GDK_BACKEND,wayland
# env = QT_QPA_PLATFORM,wayland
# env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
# env = CLUTTER_BACKEND,wayland
# env = SDL_VIDEODRIVER,wayland
# env = MOZ_ENABLE_WAYLAND,1


# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = LIBVA_DRIVER_NAME,nvidia
# env = NVD_BACKEND,direct

xwayland {
    force_zero_scaling = true
}
# cursor {
#     no_hardware_cursors = true
# }

source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/exec.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/style.conf
source = ~/.config/hypr/configs/rule.conf
