general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 2. Блокировка экрана
listener {
    timeout = 300                               # 5 минут
    on-timeout = loginctl lock-session
}

# 3. Выключение монитора — ПОСЛЕ блокировки
listener {
    timeout = 360                                # 6 минут (позже чем локскрин!)
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
