env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct

xwayland {
    force_zero_scaling = true
}

# Подгрузка остальных конфигов
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/exec.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/style.conf
source = ~/.config/hypr/configs/rule.conf
