# env = XDG_CURRENT_DESKTOP,Hyprland
# env = XDG_SESSION_TYPE,wayland
# env = XDG_SESSION_DESKTOP,Hyprland
# env = QT_QPA_PLATFORMTHEME,gtk3
# env = GTK_THEME,Adwaita-dark

source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/exec.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/style.conf
