#!/usr/bin/env bash
# setup_firefox.sh — dynamic theming for Firefox (Material Fox + DMS colors)
#
# Installs the Material Fox base theme (edelvarden/material-fox-updated) into
# every Firefox profile and wires DankMaterialShell's matugen-generated
# palette (~/.config/DankMaterialShell/firefox.css, regenerated on every
# wallpaper/theme change) as its active color layer.
#
# Resulting layout per profile:
#   chrome/userChrome.css           — Material Fox entrypoint (imports 3 layers)
#   chrome/theme-material-blue.css  — symlink to DMS firefox.css (colors)
#   user.js                         — required about:config prefs
#
# Idempotent: safe to re-run at any time.
set -euo pipefail

MATERIAL_FOX_URL="https://github.com/edelvarden/material-fox-updated/releases/download/v2.0.0/chrome.zip"
DMS_FIREFOX_CSS="$HOME/.config/DankMaterialShell/firefox.css"

# Firefox >= 147 keeps profiles in XDG config; older builds use ~/.mozilla
PROFILE_ROOTS=(
    "$HOME/.config/mozilla/firefox"
    "$HOME/.mozilla/firefox"
)

log() { printf '[firefox-theme] %s\n' "$*"; }

ensure_pref() {
    local user_js="$1" pref="$2" value="$3"
    grep -qs "user_pref(\"${pref}\"" "$user_js" || \
        echo "user_pref(\"${pref}\", ${value});" >> "$user_js"
}

setup_profile() {
    local profile="$1"
    local chrome="$profile/chrome"

    # Base theme is present when its entrypoint stylesheet exists;
    # otherwise fetch it. A stale userChrome.css symlink (e.g. from an
    # earlier broken setup) is dropped before extraction.
    if [ ! -f "$chrome/user-chrome.css" ]; then
        log "Installing Material Fox base theme into ${profile##*/}..."
        mkdir -p "$chrome"
        local tmp
        tmp="$(mktemp -d)"
        curl -fsSL -o "$tmp/chrome.zip" "$MATERIAL_FOX_URL"
        rm -f "$chrome/userChrome.css"
        unzip -oq "$tmp/chrome.zip" -d "$profile"
        rm -rf "$tmp"
    fi

    # DMS colors replace Material Fox's stock blue palette
    ln -sfn "$DMS_FIREFOX_CSS" "$chrome/theme-material-blue.css"

    ensure_pref "$profile/user.js" "toolkit.legacyUserProfileCustomizations.stylesheets" "true"
    ensure_pref "$profile/user.js" "svg.context-properties.content.enabled" "true"
    ensure_pref "$profile/user.js" "userChrome.theme-material" "true"

    if [ ! -e "$DMS_FIREFOX_CSS" ]; then
        log "NOTE: $DMS_FIREFOX_CSS does not exist yet — it is generated by DankMaterialShell on the first wallpaper/theme change."
    fi
}

main() {
    local found=0
    local root profile
    for root in "${PROFILE_ROOTS[@]}"; do
        [ -d "$root" ] || continue
        shopt -s nullglob
        for profile in "$root"/*.default* "$root"/*.Default*; do
            [ -d "$profile" ] || continue
            found=1
            setup_profile "$profile"
            log "Profile ready: ${profile}"
        done
        shopt -u nullglob
    done

    if [ "$found" -eq 0 ]; then
        log "No Firefox profiles found (run Firefox once, then re-run this script)."
        exit 0
    fi

    log "Done. Restart Firefox to apply."
}

main "$@"
