# Auto-start Applications
exec-once = easyeffects --gapplication-service
exec-once = waybar
exec-once = swww-daemon
exec-once = waypaper --restore
exec-once = swaync
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = xwaylandvideobridge
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# xrandr не работает в Wayland, убрано для совместимости с ноутом
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR XDG_CURRENT_DESKTOP
exec-once = hypridle

# Start portal backends for GNOME apps
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once = /usr/lib/xdg-desktop-portal-hyprland &
exec-once = /usr/lib/xdg-desktop-portal-gtk &

# Theme settings
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'
