$mainMod = SUPER

# Applications
bind = $mainMod, RETURN, exec, ghostty
bind = $mainMod, SPACE, exec, wofi --show drun
bind = $mainMod, B, exec, firefox
bind = $mainMod SHIFT, F, exec, nautilus
bind = $mainMod SHIFT, T, exec, ghostty -e btop
bind = , Print, exec, hyprshot -m region
bind = $mainMod, Print, exec, hyprshot -m window
bind = $mainMod SHIFT, Print, exec, hyprshot -m output
bind = $mainMod SHIFT, RETURN, exec, google-chrome-stable

# Window Management
bind = $mainMod, W, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, T, togglefloating, 
bind = $mainMod, T, resizeactive, exact 1280 720
bind = $mainMod, T, centerwindow, 
bind = $mainMod, F, fullscreen,
bind = $mainMod, G, layoutmsg, togglesplit

# Focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# --- Workspaces ---

# Toggle gaps
bind = $mainMod SHIFT, BACKSPACE, exec, hyprctl keyword general:gaps_in $(hyprctl getoption general:gaps_in -j | jq -r '.custom' | grep -q '^0 0 0 0$' && echo 5 || echo 0) && hyprctl keyword general:gaps_out $(hyprctl getoption general:gaps_out -j | jq -r '.custom' | grep -q '^0 0 0 0$' && echo 10 || echo 0)

# Переключение на воркспейсы 1-9
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Перемещение окон на воркспейсы 1-9
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9


# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d


# Уменьшить окно (SUPER и минус)
binde = $mainMod, minus, resizeactive, -40 0
binde = $mainMod SHIFT, minus, resizeactive, 0 -40

# Увеличить окно (SUPER и плюс/равно)
binde = $mainMod, equal, resizeactive, 40 0
binde = $mainMod SHIFT, equal, resizeactive, 0 40

# На случай, если плюс на твоей раскладке определяется именно как plus
binde = $mainMod, plus, resizeactive, 40 0
binde = $mainMod SHIFT, plus, resizeactive, 0 40
