windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus true
windowrule = match:class ^(neovide)$, tile true
windowrule = match:class ^(waybar)$, no_blur true

windowrule = match:class ^(org.gnome.Calendar|blueman-manager|nm-connection-editor|easyeffects|com.github.wwmm.easyeffects|org.gnome.Calculator)$, float true
windowrule = match:class ^(org.gnome.Calendar|blueman-manager|nm-connection-editor|easyeffects|com.github.wwmm.easyeffects|org.gnome.Calculator)$, center true

windowrule = match:class ^(org.gnome.Calculator)$, size 360 540

# Правила для Awakened PoE Trade (новый синтаксис Hyprland)
windowrule = match:class ^(awakened-poe-trade)$, float true
windowrule = match:class ^(awakened-poe-trade)$, pin true
windowrule = match:class ^(awakened-poe-trade)$, border_size 0
windowrule = match:class ^(awakened-poe-trade)$, no_blur true
