windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus true
windowrule = match:class ^(neovide)$, tile true
windowrule = match:class ^(waybar)$, no_blur true

windowrule = match:class ^(org.gnome.Calendar|blueman-manager|nm-connection-editor|pavucontrol)$, float true
windowrule = match:class ^(org.gnome.Calendar|blueman-manager|nm-connection-editor|pavucontrol)$, center true
