return {
  -- base46: dynamic theme generated by DankMaterialShell from wallpaper
  { "AvengeMedia/base46", lazy = true, opts = {} },

  -- Configure LazyVim to load the dms colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "dms",
    },
  },
}
