return {
  -- base46: dynamic theme generated by DankMaterialShell from wallpaper
  { "AvengeMedia/base46", lazy = true, opts = {} },

  -- Disable built-in themes we don't use (dms theme via base46 is enough)
  { "catppuccin/nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },

  -- Configure LazyVim to load the dms colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "dms",
    },
  },
}
